// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Syncra.Infrastructure;

#nullable disable

namespace Syncra.Infrastructure.Migrations
{
    [DbContext(typeof(SyncraDbContext))]
    [Migration("20260526181733_AddIdempotencyKeyTable")]
    partial class AddIdempotencyKeyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Account", b =>
                {
                    b.Property<string>("account_id")
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("account_id");

                    b.HasIndex("userId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountSnapshot", b =>
                {
                    b.Property<int>("snapshot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("snapshot_id"));

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("event_count")
                        .HasColumnType("integer");

                    b.Property<long>("snapshot_sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("snapshot_id");

                    b.HasIndex("account_id");

                    b.ToTable("AccountSnapshots");
                });

            modelBuilder.Entity("AccountState", b =>
                {
                    b.Property<string>("account_id")
                        .HasColumnType("text");

                    b.Property<decimal>("balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("last_event_id")
                        .HasColumnType("text");

                    b.Property<long>("last_server_sequence")
                        .HasColumnType("bigint");

                    b.Property<decimal>("provisional_balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.HasKey("account_id");

                    b.HasIndex("last_event_id")
                        .IsUnique();

                    b.ToTable("AccountStates");
                });

            modelBuilder.Entity("Conflict", b =>
                {
                    b.Property<int>("conflict_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("conflict_id"));

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("account_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("actual_balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("atempted_balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("compensation_event_archive_id")
                        .HasColumnType("text");

                    b.Property<string>("compensation_event_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("detected_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("original_event_archive_id")
                        .HasColumnType("text");

                    b.Property<string>("original_event_id")
                        .HasColumnType("text");

                    b.Property<int>("resolution")
                        .HasColumnType("integer");

                    b.HasKey("conflict_id");

                    b.HasIndex("account_id");

                    b.HasIndex("compensation_event_archive_id")
                        .IsUnique();

                    b.HasIndex("compensation_event_id")
                        .IsUnique();

                    b.HasIndex("original_event_archive_id")
                        .IsUnique();

                    b.HasIndex("original_event_id")
                        .IsUnique();

                    b.ToTable("Conflicts");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<string>("event_id")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("account_id")
                        .HasColumnType("text");

                    b.Property<string>("aggregateId")
                        .HasColumnType("text");

                    b.Property<int?>("caused_conflict_id")
                        .HasColumnType("integer");

                    b.Property<int?>("compensates_conflict_id")
                        .HasColumnType("integer");

                    b.Property<string>("compensates_event_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("node_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("node_sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("node_timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("parent_event_id")
                        .HasColumnType("text");

                    b.Property<long>("server_sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("server_timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("event_id");

                    b.HasIndex("account_id");

                    b.HasIndex("caused_conflict_id")
                        .IsUnique();

                    b.HasIndex("compensates_conflict_id")
                        .IsUnique();

                    b.HasIndex("compensates_event_id")
                        .IsUnique();

                    b.HasIndex("node_id");

                    b.HasIndex("parent_event_id")
                        .IsUnique();

                    b.HasIndex("server_sequence")
                        .IsUnique();

                    b.HasIndex("server_timestamp");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventArchive", b =>
                {
                    b.Property<string>("event_id")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("account_id")
                        .HasColumnType("text");

                    b.Property<int?>("caused_conflict_id")
                        .HasColumnType("integer");

                    b.Property<int?>("compensates_conflict_id")
                        .HasColumnType("integer");

                    b.Property<string>("compensates_event_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("node_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("node_sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("node_timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("parent_event_id")
                        .HasColumnType("text");

                    b.Property<long>("server_sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("server_timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("event_id");

                    b.HasIndex("account_id");

                    b.HasIndex("caused_conflict_id")
                        .IsUnique();

                    b.HasIndex("compensates_conflict_id")
                        .IsUnique();

                    b.HasIndex("compensates_event_id")
                        .IsUnique();

                    b.HasIndex("node_id");

                    b.HasIndex("parent_event_id")
                        .IsUnique();

                    b.HasIndex("server_sequence")
                        .IsUnique();

                    b.HasIndex("server_timestamp");

                    b.ToTable("EventArchives");
                });

            modelBuilder.Entity("NodeState", b =>
                {
                    b.Property<string>("node_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_seen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("last_successful_sync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("last_sync_attempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("last_synced_server_sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("local_sequence")
                        .HasColumnType("integer");

                    b.Property<int>("pending_events_count")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("node_id");

                    b.ToTable("NodeStates");
                });

            modelBuilder.Entity("Syncra.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("event_id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("response_body")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("response_status")
                        .HasColumnType("integer");

                    b.HasKey("event_id");

                    b.ToTable("IdempotencyKeys");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.HasOne("User", "user")
                        .WithMany("accounts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AccountSnapshot", b =>
                {
                    b.HasOne("Account", "account")
                        .WithMany("account_snapshots")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("AccountState", b =>
                {
                    b.HasOne("Account", "account")
                        .WithOne("account_state")
                        .HasForeignKey("AccountState", "account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event", "last_event")
                        .WithOne()
                        .HasForeignKey("AccountState", "last_event_id");

                    b.Navigation("account");

                    b.Navigation("last_event");
                });

            modelBuilder.Entity("Conflict", b =>
                {
                    b.HasOne("Account", "account")
                        .WithMany("conflicts")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventArchive", "compensation_event_archive")
                        .WithOne()
                        .HasForeignKey("Conflict", "compensation_event_archive_id");

                    b.HasOne("Event", "compensation_event")
                        .WithOne()
                        .HasForeignKey("Conflict", "compensation_event_id");

                    b.HasOne("EventArchive", "original_event_archive")
                        .WithOne()
                        .HasForeignKey("Conflict", "original_event_archive_id");

                    b.HasOne("Event", "original_event")
                        .WithOne()
                        .HasForeignKey("Conflict", "original_event_id");

                    b.Navigation("account");

                    b.Navigation("compensation_event");

                    b.Navigation("compensation_event_archive");

                    b.Navigation("original_event");

                    b.Navigation("original_event_archive");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("Account", null)
                        .WithMany("events")
                        .HasForeignKey("account_id");

                    b.HasOne("Conflict", "caused_conflict")
                        .WithOne()
                        .HasForeignKey("Event", "caused_conflict_id");

                    b.HasOne("Conflict", "compensates_conflict")
                        .WithOne()
                        .HasForeignKey("Event", "compensates_conflict_id");

                    b.HasOne("Event", "compensates_event")
                        .WithOne()
                        .HasForeignKey("Event", "compensates_event_id");

                    b.HasOne("NodeState", "node")
                        .WithMany("events")
                        .HasForeignKey("node_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Event", "parent_event")
                        .WithOne()
                        .HasForeignKey("Event", "parent_event_id");

                    b.OwnsOne("Event+EventPayloadData", "payload", b1 =>
                        {
                            b1.Property<string>("event_id")
                                .HasColumnType("text");

                            b1.Property<decimal>("amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("from_account_id")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("reason")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("to_account_id")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("event_id");

                            b1.HasIndex("from_account_id");

                            b1.HasIndex("to_account_id");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("event_id");

                            b1.HasOne("Account", "from_account")
                                .WithMany()
                                .HasForeignKey("from_account_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("Account", "to_account")
                                .WithMany()
                                .HasForeignKey("to_account_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("from_account");

                            b1.Navigation("to_account");
                        });

                    b.Navigation("caused_conflict");

                    b.Navigation("compensates_conflict");

                    b.Navigation("compensates_event");

                    b.Navigation("node");

                    b.Navigation("parent_event");

                    b.Navigation("payload")
                        .IsRequired();
                });

            modelBuilder.Entity("EventArchive", b =>
                {
                    b.HasOne("Account", null)
                        .WithMany("event_archives")
                        .HasForeignKey("account_id");

                    b.HasOne("Conflict", "caused_conflict")
                        .WithOne()
                        .HasForeignKey("EventArchive", "caused_conflict_id");

                    b.HasOne("Conflict", "compensates_conflict")
                        .WithOne()
                        .HasForeignKey("EventArchive", "compensates_conflict_id");

                    b.HasOne("EventArchive", "compensates_event")
                        .WithOne()
                        .HasForeignKey("EventArchive", "compensates_event_id");

                    b.HasOne("NodeState", "node")
                        .WithMany("eventsArchive")
                        .HasForeignKey("node_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventArchive", "parent_event")
                        .WithOne()
                        .HasForeignKey("EventArchive", "parent_event_id");

                    b.OwnsOne("EventArchive+EventArchivePayloadData", "payload", b1 =>
                        {
                            b1.Property<string>("EventArchiveevent_id")
                                .HasColumnType("text");

                            b1.Property<decimal>("amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("from_account_id")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("reason")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("to_account_id")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EventArchiveevent_id");

                            b1.HasIndex("from_account_id");

                            b1.HasIndex("to_account_id");

                            b1.ToTable("EventArchives");

                            b1.WithOwner()
                                .HasForeignKey("EventArchiveevent_id");

                            b1.HasOne("Account", "from_account")
                                .WithMany()
                                .HasForeignKey("from_account_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("Account", "to_account")
                                .WithMany()
                                .HasForeignKey("to_account_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("from_account");

                            b1.Navigation("to_account");
                        });

                    b.Navigation("caused_conflict");

                    b.Navigation("compensates_conflict");

                    b.Navigation("compensates_event");

                    b.Navigation("node");

                    b.Navigation("parent_event");

                    b.Navigation("payload")
                        .IsRequired();
                });

            modelBuilder.Entity("Syncra.Domain.Entities.IdempotencyKey", b =>
                {
                    b.HasOne("Event", "caused_event")
                        .WithOne("idempotency_record")
                        .HasForeignKey("Syncra.Domain.Entities.IdempotencyKey", "event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("caused_event");
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.Navigation("account_snapshots");

                    b.Navigation("account_state")
                        .IsRequired();

                    b.Navigation("conflicts");

                    b.Navigation("event_archives");

                    b.Navigation("events");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("idempotency_record")
                        .IsRequired();
                });

            modelBuilder.Entity("NodeState", b =>
                {
                    b.Navigation("events");

                    b.Navigation("eventsArchive");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
